[package]
name = "rpg-translator"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "RPG Maker 翻译器，支持批量翻译和特殊代码保护"

[lib]
path = "src/lib.rs"

[dependencies]
async-trait.workspace = true
rpg-parser.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true

[dev-dependencies]
tokio.workspace = true
