[package]
name = "rpg-hacker-rpg-config"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "RPG Maker 游戏修改器配置后端"
repository = ""

[dependencies]
serde.workspace = true
async-trait.workspace = true

[dev-dependencies]
tokio.workspace = true
