[workspace]
resolver = "3"
members = ["compilers/*"]
default-members = [
    "compilers/*",
]
exclude = [
    "compilers/.DS_Store",
]


[workspace.package]
edition = "2024"
version = "0.0.0"
authors = []
license = "AGPL-3.0-only"


[workspace.dependencies]
alox-48 = "0.6.0"
clap = { version = "*", features = ["derive"] }
rpg-data = { path = "compilers/rpg-data", version = "0.0.0" }

[profile.release]
lto = true
panic = "abort"
