[package]
name = "graph-editor"
version.workspace = true
authors.workspace = true
description = "Draw graph online"
repository = "https://github.com/oovm/graph-editor"
documentation = "https://docs.rs/graph-editor"
readme = "readme.md"
license.workspace = true
edition.workspace = true
exclude = ["package.json", "tests/**"]

[dependencies]

[dev-dependencies]

[features]
default = []

[package.metadata.docs.rs]
all-features = true
