[package]
name = "rpg-hacker"
version = "0.1.0"
edition = "2021"
description = "RPG Maker 游戏修改器后端"
repository = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
async-trait = "0.1"
rpg-hacker-types = { path = "../rpg-types" }
rpg-hacker-rpg-config = { path = "../rpg-config" }

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
