[package]
name = "rpg-hacker"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "RPG Maker 游戏修改器后端"
repository = ""

[dependencies]
serde.workspace = true
async-trait.workspace = true
rpg-types.workspace = true
rpg-config.workspace = true
rpg-translator.workspace = true

[dev-dependencies]
tokio.workspace = true
