[package]
name = "rpg-hacker-rgss"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "RGSS backend for rpg-hacker"

[[bin]]
name = "rpg-hacker-rgss"
path = "src/main.rs"

[dependencies]
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
bevy.workspace = true
image.workspace = true
bytemuck.workspace = true
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true

[dev-dependencies]
tokio.workspace = true

[profile.release]
opt-level = 3
lto = true

[profile.dev]
opt-level = 0

[profile.wasm-release]
inherits = "release"
opt-level = "s"
lto = true
